version: "3.9"

services:
   
   redis:
     image: redis:alpine
     container_name: redis
     ports:
       - "6379:6379"
     volumes:
       - redis-data:/data
     networks:
       - banking-network
     healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 30s
       timeout: 10s
       retries: 5


   redis-cache:
     image: redis
     container_name: redis-cache
     ports:
       - "6380:6379"
     volumes:
       - redis-cache-data:/data
     networks:
       - banking-network
     healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 30s
       timeout: 10s
       retries: 5     


   node-app:
     build: ./app
     container_name: node-app
     ports:
       - "3000:3000"
     environment:
       - REDIS_HOST=redis
       - REDIS_PORT=6379
       - REDIS_CACHE_HOST=redis-cache
       - REDIS_CACHE_PORT=6379
     volumes:
       - ./app:/app
       - /app/node_modules
     depends_on:
       redis:
         condition: service_healthy
       redis-cache:
         condition: service_healthy
     networks:
       - banking-network   

   email-worker:
    build: ./app
    command: node worker.js
    container_name: email-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - banking-network
    depends_on:
      redis:
        condition: service_healthy        


networks:
  banking-network:
    driver: bridge

volumes:
  redis-data:
  redis-cache-data: